### PR TITLE
add id tags to hotlink talks

### PR DESCRIPTION
**Pull request by rouzbeh84**
to be able to send direct links via js.la and not youtube 👍🏽

### CODE REVIEW

**Comment by ashwell** [comment]
Would it make more sense to use a simple date format for the id instead of the first speakers Github account name? That is something that could change over time, but using something like `sep-2017` or `9-2017` would be more consistent and predictable.

**Comment by ashwell** [comment]
Also, this breaks if someone gives two talks in the same year and were listed first for both events

**Comment by rouzbeh84** [comment]
yea, i was mainly limited to jade looping and not wanting `/` or ` ` in the id haha. i started with `event.date` but couldn't splice/join on it within `jade` afaik

**Comment by ashwell** [comment]
I'm not well versed in jade but I thought there was a way to define a javascript function inside the template and use it inline. So you could do something like `(id =getDateSlug( event.datetime ))` and define `getDateSlug` at the top of the file, which would return the `9-2017` id value.

pinging @davidguttman for his Jade knowledge

**Comment by ashwell** [comment]
looks like you can based on [these docs](https://pugjs.org/language/code.html)

```jade
- function getDateSlug( date ) { return ( date.getMonth() + 1 ) + '-' + date.getFullYear(); }
#  later
h2(id= getDateSlug(event.datetime))= event.datetime
```

I'm just guessing here tho...

**Pull request merged**
