### PR TITLE
Update for June

### PR DESCRIPTION
**Pull request by seanwestfall**
Update for the June Meetup
* Still waiting on who the Sponsors are
* Also need the description for the second speaker

### CODE REVIEW

**Comment by jcblw** [comment]
hey can we move over the existing event to the archive? its in events -> 2017 -> _data.json

**Comment by jcblw** [comment]
also I think Samy info is now in our db, we are thinking about announcing next week. Thanks for putting this together so quickly.

**Comment by seanwestfall** [comment]
@jcblw added Samy's info to the _data.json file.

**Comment by jcblw** [comment]
looks pretty good @seanwestfall I think tho we should set the current drinks js to `null` to avoid showing the wrong location.

**Comment by seanwestfall** [comment]
@jcblw K, I removed all the data for drinks.js. :+1: I think this should be good to go when ever you want to do the announcement.

**Comment by jcblw** [comment]
ok no reason to sit on it, gonna merge it now

**Pull request merged**
