### PR TITLE
Update for April 27, 2017 Meetup

### PR DESCRIPTION
**Pull request by seanwestfall**
There still might be a few changes that need to be made.
- The images haven't been through the speakerimages task, since there seems to be a dependency problem with lwip.
- For the first talk, since Lauren Spiegel is speaking _with_ Giorgio Regni, maybe there should be two avatars/github-links/twitter-links.
- drinksjs still has to be updated.

### CODE REVIEW

**Comment by jcblw** [comment]
🙌 looks great, I'm gonna hold off and merge this tonight after I create the tito event for this month.

The speaker image stuff is fine you can actually do it using [imagemagik](https://www.imagemagick.org/script/index.php) directly, but its not required to get this out the door.

```
convert public/images/speakers/$FILENAME.$FILEEXT -resize 160x160^ -gravity center -background #FFFFFF -extent 160x160 public/images/speakers/$FILENAME.jpg
```

**Comment by ashwell** [comment]
@jcblw does the April event data need to be put into `public/events/2017/_data.json` or does that normally happen at a later date?

**Comment by Omarcito** [comment]
@ashwell I normally copy that over when i do the videos PR

**Comment by ashwell** [comment]
@Omarcito ahh cool, I was thinking that was the case but wanted to be sure

**Comment by jcblw** [comment]
@ashwell yeah checked that out before hand. @Omarcito 💪

**Pull request merged**
