### PR TITLE
Fixed and added new Event photos

### PR DESCRIPTION
**Pull request by Spencer-Allen**
Turns out someone else started using the JSLA tag for some random event, and photos were finding their way in. Changed the Tag to something a bit more obscure, and 2x checked all of the past event JSON entries.

### CODE REVIEW

**Comment by jcblw** [comment]
:raised_hands: yes! I love photo updates :heart:

**Comment by Spencer-Allen** [comment]
Curious if there was a problem found with this pull request, or if it just fell by the wayside.

**Comment by jcblw** [comment]
sorry just fell wayside Ill pick this back up tonight

**Comment by Spencer-Allen** [comment]
No worries :) thanks!!

**Comment by jcblw** [comment]
sry for the delay everything it up!

**Pull request merged**
