### PR TITLE
update faq

### PR DESCRIPTION
**Pull request by rouzbeh84**
add some more info for rsvp/waitlist

add id to headers for easy hotlinks

### CODE REVIEW

**Comment by jcblw** [comment]
👍

**Comment by rouzbeh84** [comment]
just following up on this. are we going to restructure the site a bit with some pared down pages and toss this into the about section? we lightly touched on this in the last meeting but not sure where we landed.

**Comment by jcblw** [comment]
@rouzbeh84 I think you can just replace the link to about since we do not need it anymore.

**Comment by jcblw** [comment]
dude merging

**Pull request merged**
